### ISSUE TITLE
TvOS Support

### ISSUE THREAD

**Issue by toygar-zzz** [marmelroy/TVButton#2]

**Comment by marmelroy** [comment]
Hi Toygar, the purpose of TVButton is to bring the parallax icons from tvOS to iOS. tvOS support is not on the cards...

**Comment by toygar-zzz** [comment]
thanks

**Comment by ghost** [comment]
:+1:  for tvOS support. Would love to use this in my tvOS app for a couple of buttons and Apple doesn't include it natively yet.

**Comment by marmelroy** [comment]
Hey @NitWitStudios, it's still out of scope for TVButton but could be an interesting separate project...
